import type { Metadata } from "next";
import "./globals.css";
import { Noto_Sans_Bengali } from 'next/font/google';
import { Toaster } from "react-hot-toast";
import ReduxProvider from "./provider/ReduxProvider";

const bengaliFont = Noto_Sans_Bengali({
  subsets: ['bengali'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: "লাইভ ভোটিং",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={bengaliFont.className}
      >
        <ReduxProvider>
         {children}
        </ReduxProvider>
        <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}
